admin_user_name: smittyman
admin_user_groups: ["sudo"]
admin_passwordless_sudo: true
base_timezone: "America/New_York"

admin_authorized_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINXdpbaJuNTaMFItt4F2FYW0eD3HQ1yw864KlNLK83AN 1973m@Computron"
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKqYo8kJuQDH1CWZ+gUbVA6Dl8rH/D1lEdggE8deaGIk smittyman@home.arpa"