$ANSIBLE_VAULT;1.1;AES256
30633163306237633764306165653931343531333164643837626334353866636562653438323133
3738633539646163323764626230386632323463343535360a633565353234333639633739616436
63633766663766303065663863313064616138343666346139616465643563333032326135336236
6266383166373265390a633934313066663935363538323236316364613962323132653137663438
62336562616638636235353331356431326236633632333339333430616431373765
